### ISSUE TITLE
GPU issue while training

### ISSUE THREAD

**Issue by vsaisimha97** [UKPLab/e2e-nlg-challenge-2017#1]
AssertionError: 
The NVIDIA driver on your system is too old (found version 10010).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

**Comment by ypuzikov** [comment]
Thanks for pointing that out! 
The project was written almost 3 years ago as a prototype. I have not used it since :) 
Not only the driver, but also the Python dependencies are outdated. I will look into that later this week!

**Comment by ypuzikov** [comment]
@vsaisimha97 , does it solve the issue for you?
